const forecast = [
  {
    Headline: {
      EffectiveDate: "2022-05-29T08:00:00+01:00",
      EffectiveEpochDate: 1653807600,
      Severity: 5,
      Text: "Expect showers Sunday",
      Category: "rain",
      EndDate: "2022-05-29T20:00:00+01:00",
      EndEpochDate: 1653850800,
      MobileLink:
        "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
      Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?lang=en-us",
    },
    DailyForecasts: [
      {
        Date: "2022-05-26T07:00:00+01:00",
        EpochDate: 1653544800,
        Sun: {
          Rise: "2022-05-26T04:55:00+01:00",
          EpochRise: 1653537300,
          Set: "2022-05-26T21:01:00+01:00",
          EpochSet: 1653595260,
        },
        Moon: {
          Rise: "2022-05-26T03:33:00+01:00",
          EpochRise: 1653532380,
          Set: "2022-05-26T16:41:00+01:00",
          EpochSet: 1653579660,
          Phase: "WaningCrescent",
          Age: 26,
        },
        Temperature: {
          Minimum: {
            Value: 52,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 69,
            Unit: "F",
            UnitType: 18,
          },
        },
        RealFeelTemperature: {
          Minimum: {
            Value: 50,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 66,
            Unit: "F",
            UnitType: 18,
            Phrase: "Pleasant",
          },
        },
        RealFeelTemperatureShade: {
          Minimum: {
            Value: 50,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
          Maximum: {
            Value: 65,
            Unit: "F",
            UnitType: 18,
            Phrase: "Pleasant",
          },
        },
        HoursOfSun: 1.1,
        DegreeDaySummary: {
          Heating: {
            Value: 5,
            Unit: "F",
            UnitType: 18,
          },
          Cooling: {
            Value: 0,
            Unit: "F",
            UnitType: 18,
          },
        },
        AirAndPollen: [
          {
            Name: "AirQuality",
            Value: 0,
            Category: "Good",
            CategoryValue: 1,
            Type: "Ozone",
          },
          {
            Name: "Grass",
            Value: 4,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Mold",
            Value: 32767,
            Category: "High",
            CategoryValue: 3,
          },
          {
            Name: "Tree",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Ragweed",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "UVIndex",
            Value: 2,
            Category: "Low",
            CategoryValue: 1,
          },
        ],
        Day: {
          Icon: 6,
          IconPhrase: "Mostly cloudy",
          HasPrecipitation: false,
          ShortPhrase: "Mostly cloudy and breezy",
          LongPhrase: "Mostly cloudy and breezy",
          PrecipitationProbability: 25,
          ThunderstormProbability: 0,
          RainProbability: 25,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 15,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 256,
              Localized: "WSW",
              English: "WSW",
            },
          },
          WindGust: {
            Speed: {
              Value: 34,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 256,
              Localized: "WSW",
              English: "WSW",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 95,
          Evapotranspiration: {
            Value: 0.1,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 4233.8,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Night: {
          Icon: 35,
          IconPhrase: "Partly cloudy",
          HasPrecipitation: false,
          ShortPhrase: "Breezy early; partly cloudy",
          LongPhrase: "Breezy this evening; otherwise, partly cloudy",
          PrecipitationProbability: 16,
          ThunderstormProbability: 0,
          RainProbability: 16,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 10,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 271,
              Localized: "W",
              English: "W",
            },
          },
          WindGust: {
            Speed: {
              Value: 25,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 271,
              Localized: "W",
              English: "W",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 45,
          Evapotranspiration: {
            Value: 0.02,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 933.5,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Sources: ["AccuWeather"],
        MobileLink:
          "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&lang=en-us",
        Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=1&lang=en-us",
      },
      {
        Date: "2022-05-27T07:00:00+01:00",
        EpochDate: 1653631200,
        Sun: {
          Rise: "2022-05-27T04:54:00+01:00",
          EpochRise: 1653623640,
          Set: "2022-05-27T21:02:00+01:00",
          EpochSet: 1653681720,
        },
        Moon: {
          Rise: "2022-05-27T03:46:00+01:00",
          EpochRise: 1653619560,
          Set: "2022-05-27T17:55:00+01:00",
          EpochSet: 1653670500,
          Phase: "WaningCrescent",
          Age: 27,
        },
        Temperature: {
          Minimum: {
            Value: 48,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 66,
            Unit: "F",
            UnitType: 18,
          },
        },
        RealFeelTemperature: {
          Minimum: {
            Value: 44,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 69,
            Unit: "F",
            UnitType: 18,
            Phrase: "Pleasant",
          },
        },
        RealFeelTemperatureShade: {
          Minimum: {
            Value: 44,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 63,
            Unit: "F",
            UnitType: 18,
            Phrase: "Pleasant",
          },
        },
        HoursOfSun: 4.8,
        DegreeDaySummary: {
          Heating: {
            Value: 8,
            Unit: "F",
            UnitType: 18,
          },
          Cooling: {
            Value: 0,
            Unit: "F",
            UnitType: 18,
          },
        },
        AirAndPollen: [
          {
            Name: "AirQuality",
            Value: 0,
            Category: "Good",
            CategoryValue: 1,
            Type: "Ozone",
          },
          {
            Name: "Grass",
            Value: 12,
            Category: "Moderate",
            CategoryValue: 2,
          },
          {
            Name: "Mold",
            Value: 32767,
            Category: "High",
            CategoryValue: 3,
          },
          {
            Name: "Tree",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Ragweed",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "UVIndex",
            Value: 7,
            Category: "High",
            CategoryValue: 3,
          },
        ],
        Day: {
          Icon: 4,
          IconPhrase: "Intermittent clouds",
          HasPrecipitation: false,
          ShortPhrase: "Periods of sun",
          LongPhrase: "Periods of sun",
          PrecipitationProbability: 1,
          ThunderstormProbability: 0,
          RainProbability: 1,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 10,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 307,
              Localized: "NW",
              English: "NW",
            },
          },
          WindGust: {
            Speed: {
              Value: 21,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 307,
              Localized: "NW",
              English: "NW",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 46,
          Evapotranspiration: {
            Value: 0.14,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 8511.7,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Night: {
          Icon: 35,
          IconPhrase: "Partly cloudy",
          HasPrecipitation: false,
          ShortPhrase: "Partly cloudy",
          LongPhrase: "Partly cloudy",
          PrecipitationProbability: 2,
          ThunderstormProbability: 0,
          RainProbability: 2,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 9,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 329,
              Localized: "NNW",
              English: "NNW",
            },
          },
          WindGust: {
            Speed: {
              Value: 24,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 329,
              Localized: "NNW",
              English: "NNW",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 41,
          Evapotranspiration: {
            Value: 0.03,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 1147.5,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Sources: ["AccuWeather"],
        MobileLink:
          "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&lang=en-us",
        Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=2&lang=en-us",
      },
      {
        Date: "2022-05-28T07:00:00+01:00",
        EpochDate: 1653717600,
        Sun: {
          Rise: "2022-05-28T04:53:00+01:00",
          EpochRise: 1653709980,
          Set: "2022-05-28T21:03:00+01:00",
          EpochSet: 1653768180,
        },
        Moon: {
          Rise: "2022-05-28T04:00:00+01:00",
          EpochRise: 1653706800,
          Set: "2022-05-28T19:08:00+01:00",
          EpochSet: 1653761280,
          Phase: "WaningCrescent",
          Age: 28,
        },
        Temperature: {
          Minimum: {
            Value: 46,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 64,
            Unit: "F",
            UnitType: 18,
          },
        },
        RealFeelTemperature: {
          Minimum: {
            Value: 45,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 66,
            Unit: "F",
            UnitType: 18,
            Phrase: "Pleasant",
          },
        },
        RealFeelTemperatureShade: {
          Minimum: {
            Value: 45,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 61,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
        },
        HoursOfSun: 7.5,
        DegreeDaySummary: {
          Heating: {
            Value: 10,
            Unit: "F",
            UnitType: 18,
          },
          Cooling: {
            Value: 0,
            Unit: "F",
            UnitType: 18,
          },
        },
        AirAndPollen: [
          {
            Name: "AirQuality",
            Value: 0,
            Category: "Good",
            CategoryValue: 1,
            Type: "Ozone",
          },
          {
            Name: "Grass",
            Value: 12,
            Category: "Moderate",
            CategoryValue: 2,
          },
          {
            Name: "Mold",
            Value: 32767,
            Category: "High",
            CategoryValue: 3,
          },
          {
            Name: "Ragweed",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Tree",
            Value: 3,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "UVIndex",
            Value: 5,
            Category: "Moderate",
            CategoryValue: 2,
          },
        ],
        Day: {
          Icon: 4,
          IconPhrase: "Intermittent clouds",
          HasPrecipitation: false,
          ShortPhrase: "Times of sun and clouds",
          LongPhrase: "Times of sun and clouds",
          PrecipitationProbability: 2,
          ThunderstormProbability: 0,
          RainProbability: 2,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 9.2,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 5,
              Localized: "N",
              English: "N",
            },
          },
          WindGust: {
            Speed: {
              Value: 20.7,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 5,
              Localized: "N",
              English: "N",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 65,
          Evapotranspiration: {
            Value: 0.12,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 2498.9,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Night: {
          Icon: 34,
          IconPhrase: "Mostly clear",
          HasPrecipitation: false,
          ShortPhrase: "Mainly clear",
          LongPhrase: "Mainly clear",
          PrecipitationProbability: 3,
          ThunderstormProbability: 0,
          RainProbability: 3,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 6.9,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 8,
              Localized: "N",
              English: "N",
            },
          },
          WindGust: {
            Speed: {
              Value: 17.3,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 25,
              Localized: "NNE",
              English: "NNE",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 13,
          Evapotranspiration: {
            Value: 0.02,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 810.1,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Sources: ["AccuWeather"],
        MobileLink:
          "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&lang=en-us",
        Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=3&lang=en-us",
      },
      {
        Date: "2022-05-29T07:00:00+01:00",
        EpochDate: 1653804000,
        Sun: {
          Rise: "2022-05-29T04:52:00+01:00",
          EpochRise: 1653796320,
          Set: "2022-05-29T21:04:00+01:00",
          EpochSet: 1653854640,
        },
        Moon: {
          Rise: "2022-05-29T04:17:00+01:00",
          EpochRise: 1653794220,
          Set: "2022-05-29T20:21:00+01:00",
          EpochSet: 1653852060,
          Phase: "WaningCrescent",
          Age: 29,
        },
        Temperature: {
          Minimum: {
            Value: 46,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 58,
            Unit: "F",
            UnitType: 18,
          },
        },
        RealFeelTemperature: {
          Minimum: {
            Value: 45,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 56,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
        },
        RealFeelTemperatureShade: {
          Minimum: {
            Value: 45,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 54,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
        },
        HoursOfSun: 2.4,
        DegreeDaySummary: {
          Heating: {
            Value: 13,
            Unit: "F",
            UnitType: 18,
          },
          Cooling: {
            Value: 0,
            Unit: "F",
            UnitType: 18,
          },
        },
        AirAndPollen: [
          {
            Name: "AirQuality",
            Value: 0,
            Category: "Good",
            CategoryValue: 1,
            Type: "Ozone",
          },
          {
            Name: "Grass",
            Value: 9,
            Category: "Moderate",
            CategoryValue: 2,
          },
          {
            Name: "Mold",
            Value: 32767,
            Category: "High",
            CategoryValue: 3,
          },
          {
            Name: "Ragweed",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Tree",
            Value: 7,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "UVIndex",
            Value: 2,
            Category: "Low",
            CategoryValue: 1,
          },
        ],
        Day: {
          Icon: 6,
          IconPhrase: "Mostly cloudy",
          HasPrecipitation: true,
          PrecipitationType: "Rain",
          PrecipitationIntensity: "Light",
          ShortPhrase: "Variable clouds with a shower",
          LongPhrase: "Variable clouds with a shower in places",
          PrecipitationProbability: 40,
          ThunderstormProbability: 8,
          RainProbability: 40,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 10.4,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 360,
              Localized: "N",
              English: "N",
            },
          },
          WindGust: {
            Speed: {
              Value: 23,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 358,
              Localized: "N",
              English: "N",
            },
          },
          TotalLiquid: {
            Value: 0.02,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0.02,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 1,
          HoursOfRain: 1,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 86,
          Evapotranspiration: {
            Value: 0.09,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 1768.7,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Night: {
          Icon: 38,
          IconPhrase: "Mostly cloudy",
          HasPrecipitation: false,
          ShortPhrase: "Becoming cloudy",
          LongPhrase: "Becoming cloudy",
          PrecipitationProbability: 22,
          ThunderstormProbability: 0,
          RainProbability: 22,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 5.8,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 325,
              Localized: "NW",
              English: "NW",
            },
          },
          WindGust: {
            Speed: {
              Value: 20.7,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 7,
              Localized: "N",
              English: "N",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 75,
          Evapotranspiration: {
            Value: 0.01,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 380,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Sources: ["AccuWeather"],
        MobileLink:
          "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&lang=en-us",
        Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=4&lang=en-us",
      },
      {
        Date: "2022-05-30T07:00:00+01:00",
        EpochDate: 1653890400,
        Sun: {
          Rise: "2022-05-30T04:51:00+01:00",
          EpochRise: 1653882660,
          Set: "2022-05-30T21:06:00+01:00",
          EpochSet: 1653941160,
        },
        Moon: {
          Rise: "2022-05-30T04:38:00+01:00",
          EpochRise: 1653881880,
          Set: "2022-05-30T21:32:00+01:00",
          EpochSet: 1653942720,
          Phase: "New",
          Age: 0,
        },
        Temperature: {
          Minimum: {
            Value: 47,
            Unit: "F",
            UnitType: 18,
          },
          Maximum: {
            Value: 59,
            Unit: "F",
            UnitType: 18,
          },
        },
        RealFeelTemperature: {
          Minimum: {
            Value: 47,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 59,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
        },
        RealFeelTemperatureShade: {
          Minimum: {
            Value: 47,
            Unit: "F",
            UnitType: 18,
            Phrase: "Chilly",
          },
          Maximum: {
            Value: 57,
            Unit: "F",
            UnitType: 18,
            Phrase: "Cool",
          },
        },
        HoursOfSun: 1.5,
        DegreeDaySummary: {
          Heating: {
            Value: 12,
            Unit: "F",
            UnitType: 18,
          },
          Cooling: {
            Value: 0,
            Unit: "F",
            UnitType: 18,
          },
        },
        AirAndPollen: [
          {
            Name: "AirQuality",
            Value: 0,
            Category: "Good",
            CategoryValue: 1,
            Type: "Ozone",
          },
          {
            Name: "Grass",
            Value: 6,
            Category: "Moderate",
            CategoryValue: 2,
          },
          {
            Name: "Mold",
            Value: 32767,
            Category: "High",
            CategoryValue: 3,
          },
          {
            Name: "Ragweed",
            Value: 0,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "Tree",
            Value: 7,
            Category: "Low",
            CategoryValue: 1,
          },
          {
            Name: "UVIndex",
            Value: 2,
            Category: "Low",
            CategoryValue: 1,
          },
        ],
        Day: {
          Icon: 13,
          IconPhrase: "Mostly cloudy w/ showers",
          HasPrecipitation: true,
          PrecipitationType: "Rain",
          PrecipitationIntensity: "Light",
          ShortPhrase: "A couple of showers",
          LongPhrase: "Variable clouds with a couple of showers",
          PrecipitationProbability: 84,
          ThunderstormProbability: 17,
          RainProbability: 84,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 6.9,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 343,
              Localized: "NNW",
              English: "NNW",
            },
          },
          WindGust: {
            Speed: {
              Value: 17.3,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 285,
              Localized: "WNW",
              English: "WNW",
            },
          },
          TotalLiquid: {
            Value: 0.12,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0.12,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 2,
          HoursOfRain: 2,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 90,
          Evapotranspiration: {
            Value: 0.08,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 1645.3,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Night: {
          Icon: 7,
          IconPhrase: "Cloudy",
          HasPrecipitation: false,
          ShortPhrase: "Plenty of clouds",
          LongPhrase: "Plenty of clouds",
          PrecipitationProbability: 25,
          ThunderstormProbability: 0,
          RainProbability: 25,
          SnowProbability: 0,
          IceProbability: 0,
          Wind: {
            Speed: {
              Value: 4.6,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 167,
              Localized: "SSE",
              English: "SSE",
            },
          },
          WindGust: {
            Speed: {
              Value: 13.8,
              Unit: "mi/h",
              UnitType: 9,
            },
            Direction: {
              Degrees: 151,
              Localized: "SSE",
              English: "SSE",
            },
          },
          TotalLiquid: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Rain: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Snow: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          Ice: {
            Value: 0,
            Unit: "in",
            UnitType: 1,
          },
          HoursOfPrecipitation: 0,
          HoursOfRain: 0,
          HoursOfSnow: 0,
          HoursOfIce: 0,
          CloudCover: 97,
          Evapotranspiration: {
            Value: 0.01,
            Unit: "in",
            UnitType: 1,
          },
          SolarIrradiance: {
            Value: 284.3,
            Unit: "W/m²",
            UnitType: 33,
          },
        },
        Sources: ["AccuWeather"],
        MobileLink:
          "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&lang=en-us",
        Link: "http://www.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day=5&lang=en-us",
      },
    ],
  },
];
export default forecast;
